version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin       # Set root password
      MYSQL_DATABASE: store          # Password for 'admin' user
    ports:
      - "3306:3306"                    # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql      # Persist MySQL data

volumes:
  mysql_data:
